stages:
  - build
  - deploy

build:
  image: node:latest    
  stage: build
  variables: 
    # Replace this with your site URL
    PUBLIC_URL: https://gitlab.com/dietex1/insurance-company
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - npm install    
    - npm run build
  artifacts:
    paths:
      - build/    
  only:
    - main

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
    NODE_ENV: production
    PUBLIC_URL: https://gitlab.com/dietex1/insurance-company
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public
  only:
    - main
